### ISSUE TITLE
KeyError: 21

### ISSUE THREAD

**Issue by Mar-Gra-creator** [psipred/DMPfold2#3]
hey
I have an issue:
Traceback (most recent call last):
  File "/home/marcin/anaconda3/envs/dmpfold2/bin/dmpfold", line 5, in <module>
    run_dmpfold()
  File "/home/marcin/anaconda3/envs/dmpfold2/lib/python3.8/site-packages/dmpfold/predict.py", line 202, in run_dmpfold
    atomnum, an, rnamedict[alnmat[0,ri]], ri + 1,
KeyError: 21

Do you know what could be wrong?

I use dmpfold2 on cpu
	0: AMD Ryzen 9 3950X
Microarchitectures:
	32x Zen 2
<32gb RAM

**Comment by andymlau** [comment]
Hi, usually this means that there's a gap character ('-') in the query sequence/first line of the alignment which DMPfold2 isn't set up to model. Could you try running it again without the gap?

**Comment by Mar-Gra-creator** [comment]
Thanks it works :)
