### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Mar-Gra-creator** [psipred/DMPfold2#4]
Hey again
Another problem... I want to run dmpfold2 on other computer and get this:

(dmpfold) marcin@marcin-Precision-7920-Tower:/mnt/7fee140a-a85e-4bbb-96b1-4a34cdb806c1$                                                                         dmpfold -i PF10963.aln -d cuda:0 > fold.pdb
Traceback (most recent call last):
  File "/home/marcin/anaconda3/envs/dmpfold/bin/dmpfold", line 5, in <module>
    run_dmpfold()
  File "/home/marcin/anaconda3/envs/dmpfold/lib/python3.8/site-packages/dmpfold/predict.py", line 184, in run_dmpfold
    coords, confs, alnmat = aln_to_coords(args.input_file, device=args.device,
  File "/home/marcin/anaconda3/envs/dmpfold/lib/python3.8/site-packages/dmpfold/predict.py", line 128, in aln_to_coords
    alnmat = (np.frombuffer(''.join(aln).translate(aa_trans).encode('latin-1'), dtype=np.uint8) - ord('A')).reshape(nseqs,length)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u21b5' in position 102630: ordinal not in range(256)
(dmpfold) marcin@marcin-Precision-7920-Tower:/mnt/7fee140a-a85e-4bbb-96b1-4a34cdb806c1$

do you know what could be wrong?
all best
Marcin

Update
its my fault, bad input

**Comment by jgreener64** [comment]
Sounds like you worked out the problem - there were special characters in the input file.
